=== JMMC-OpenDev/oiexplorer/oiexplorer-core/src/fr/jmmc/oiexplorer/core/model/PlotDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
*******************************************************************************
* JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
*******************************************************************************
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.jmmc.fr/oiexplorer-core-plot-definition/0.1"
            targetNamespace="http://www.jmmc.fr/oiexplorer-core-plot-definition/0.1"
            xmlns:b="http://www.jmmc.fr/oiexplorer-base/0.1"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
            xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
            jaxb:version="2.1" jaxb:extensionBindingPrefixes="xjc">

    <xsd:annotation>
        <xsd:documentation>
            This xml schema describes the plot definitions for oiexplorer-core plots.
        </xsd:documentation>
        <xsd:appinfo>
            <!--
                Comment the jaxb:globalBindings element in embedded xml schema used with XJC               
            -->
            <!--
            <jaxb:globalBindings>                 
                <xjc:simple />
            </jaxb:globalBindings>            
            -->
            <jaxb:schemaBindings>
                <jaxb:package name="fr.jmmc.oiexplorer.core.model.plot"/>
            </jaxb:schemaBindings>
        </xsd:appinfo>
    </xsd:annotation>


    <xsd:import namespace="http://www.jmmc.fr/oiexplorer-base/0.1" schemaLocation="./OIBase.xsd"/>


    <!-- Elements -->
    <xsd:element name="plotDefinitions" type="PlotDefinitions">
        <xsd:annotation>
            <xsd:documentation>
                this element contains a list of plot definition.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>



    <!-- Class Types -->
    <xsd:complexType name="PlotDefinitions">
        <xsd:annotation>
            <xsd:documentation>
                This type describes a list plot definition.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="plotDefinition" type="PlotDefinition" minOccurs="1" maxOccurs="unbounded"/>            
        </xsd:sequence>
    </xsd:complexType>

    
        
                
    <xsd:complexType name="PlotDefinition">
        <xsd:annotation>
            <xsd:documentation>
                This type describes a plot definition.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexContent>
            <xsd:extension base="b:Identifiable">
                <xsd:sequence>

                    <xsd:element name="skipFlaggedData" type="xsd:boolean"> 
                        <xsd:annotation>
                            <xsd:documentation>
                                Indicates that flagged data are not plotted.
                            </xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>                            

                    <xsd:element name="drawLine" type="xsd:boolean"> 
                        <xsd:annotation>
                            <xsd:documentation>
                                Indicates to draw line between data point of the same serie.
                            </xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>

                    <!-- use a specialized colorAxis ?? to use custom value to encode color (linear / log) ... -->
                    <xsd:element name="colorMapping" type="ColorMapping" minOccurs="1" maxOccurs="1">
                        <xsd:annotation>
                            <xsd:documentation>
                                Color mapping (enumerated value)
                            </xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>            
                    
                    <!-- TODO: group by or split by baseline, configuration, dateObs -->

                    <xsd:element name="xAxis" type="Axis" minOccurs="1" maxOccurs="1"/>

                    <xsd:element name="yAxes" type="Axis" minOccurs="1" maxOccurs="unbounded"/>

                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
  
  
  
    <xsd:complexType name="Axis">
        <xsd:annotation>
            <xsd:documentation>
                This type describes a plot axis.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
        
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        Label of column to associate on the plot axis.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>            
            
            <xsd:element name="logScale" type="xsd:boolean">
                <xsd:annotation>
                    <xsd:documentation>
                        Use logarithm scale on the plot axis.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        
            <xsd:element name="includeZero" type="xsd:boolean">
                <xsd:annotation>
                    <xsd:documentation>
                        Request to display the zero of plot axis (may be overidden by range).
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        
            <xsd:element name="plotError" type="xsd:boolean" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        Request to plot errors if they exist.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        
            <xsd:element name="range" type="Range" minOccurs="0" maxOccurs="1">
            </xsd:element>
                
            <!-- TODO enum fonction -->
            <!-- TODO unit conversion -->
            <xsd:element name="converter" type="xsd:string" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>
                        Converter key associated to this axis
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>            
                                                  
        </xsd:sequence>
    </xsd:complexType>
 
 

 
    <xsd:complexType name="Range">
        <xsd:annotation>
            <xsd:documentation>
                This type describes an axis range.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="min" type="xsd:double" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="max" type="xsd:double" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>




  <!-- enumerations -->
  <!-- TODO: ViewType (table, plot ...) -->
  
  <!-- ColorMapping -->
  <xsd:simpleType name="ColorMapping">
    <xsd:annotation>
      <xsd:documentation>
        Possible values for the color mapping :
        - WavelengthRange (EFF_WAVE)
        - StationIndex (STA_INDEX) (baseline or triplet)
        - Configuration (STA_CONF)
        - ObservationDate (DATE_OBS)          
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="WavelengthRange">
        <xsd:annotation>
          <xsd:documentation>'WavelengthRange' indicates to use the effective wave length (EFF_WAVE)</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="StationIndex">
        <xsd:annotation>
          <xsd:documentation>'StationIndex' indicates to use the station index array (STA_INDEX) (baseline or triplet)</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="Configuration">
        <xsd:annotation>
          <xsd:documentation>'Configuration' indicates to use the station configuration (STA_CONF)</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="ObservationDate">
        <xsd:annotation>
          <xsd:documentation>'ObservationDate' indicates to use the observation date (DATE_OBS)</xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>

  
</xsd:schema>

=== JMMC-OpenDev/oiexplorer/oiexplorer-core/src/fr/jmmc/oiexplorer/core/resource/plotDefinitionPresets.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
*******************************************************************************
* JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
*******************************************************************************
-->

<!--
  This file describes a set of plotdefinition to be used has plot configuration presets 
-->
<p:plotDefinitions
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:p='http://www.jmmc.fr/oiexplorer-core-plot-definition/0.1'
    xsi:schemaLocation='http://www.jmmc.fr/oiexplorer-core-plot-definition/0.1 ../model/PlotDefinition.xsd'>
    
   
    <!-- Changes to this file should get ATTENTION                                        -->           
    <!-- first OIfitsExplorer versions may store plotDefinition with the historical names -->
    <!-- Ids should be added to replace name (and accept whole characters...)             -->

    <!-- plot spatial(UCOORD VCOORD) -->    
    <plotDefinition>
        <id>VCOORD_SPATIAL/UCOORD_SPATIAL</id>
        <name>Spatial UCOORD - VCOORD coverage</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>UCOORD_SPATIAL</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
            <converter>MEGA_LAMBDA</converter>
        </xAxis>
        <yAxes>
            <name>VCOORD_SPATIAL</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
            <converter>MEGA_LAMBDA</converter>
        </yAxes>
    </plotDefinition>




    <!-- plot (Vis2 / T3phi) vs spatial freq -->    
    <plotDefinition>
        <id>VIS2DATA_T3PHI/SPATIAL_FREQ</id>
        <name>Vis2Data and T3Phi vs. Spatial freq.</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>SPATIAL_FREQ</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
            <converter>MEGA_LAMBDA</converter>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>T3PHI</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>
    
    <!-- plot (Vis2 / T3phi) vs radius -->    
    <plotDefinition>
        <id>VIS2DATA_T3PHI/RADIUS</id>
        <name>Vis2Data and T3Phi vs. Radius</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>RADIUS</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>T3PHI</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>
    
    <!-- plot (Vis2 / T3phi) vs angle -->    
    <plotDefinition>
        <id>VIS2DATA_T3PHI/POS_ANGLE</id>
        <name>Vis2Data and T3Phi vs. Pos. angle</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>POS_ANGLE</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>T3PHI</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>
    
    <!-- plot(Vis2 - T3) vs wavelength -->    
    <plotDefinition>
        <id>VIS2DATA_T3PHI/EFF_WAVE</id>
        <name>Vis2Data and T3Phi vs. Eff. Wave</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>EFF_WAVE</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
            <converter>MICRO_METER</converter>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>T3PHI</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>
    
    <!-- plot(Vis2 - T3) vs hour angle -->
    <plotDefinition>
        <id>VIS2DATA_T3PHI/HOUR_ANGLE</id>
        <name>Vis2Data and T3Phi vs. Hour angle</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>HOUR_ANGLE</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>T3PHI</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>




    <!-- plot (Vis2 / VisAmp) vs spatial freq -->    
    <plotDefinition>
        <id>VIS2DATA_VISAMP/SPATIAL_FREQ</id>
        <name>Vis2Data and VisAmp vs. Spatial freq.</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>SPATIAL_FREQ</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
            <converter>MEGA_LAMBDA</converter>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>VISAMP</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>
    
    <!-- plot (Vis2 / VisAmp) vs radius -->    
    <plotDefinition>
        <id>VIS2DATA_VISAMP/RADIUS</id>
        <name>Vis2Data and VisAmp vs. Radius</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>RADIUS</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>VISAMP</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>
    
    <!-- plot (Vis2 / VisAmp) vs angle -->    
    <plotDefinition>
        <id>VIS2DATA_VISAMP/POS_ANGLE</id>
        <name>Vis2Data and VisAmp vs. Pos. angle</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>POS_ANGLE</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>VISAMP</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>
    
    <!-- plot(Vis2 / VisAmp) vs wavelength -->    
    <plotDefinition>
        <id>VIS2DATA_VISAMP/EFF_WAVE</id>
        <name>Vis2Data and VisAmp vs. Eff. Wave</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>EFF_WAVE</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
            <converter>MICRO_METER</converter>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>VISAMP</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>
    
    <!-- plot(Vis2 / VisAmp) vs hour angle -->
    <plotDefinition>
        <id>VIS2DATA_VISAMP/HOUR_ANGLE</id>
        <name>Vis2Data and VisAmp vs. Hour angle</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>HOUR_ANGLE</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
        </xAxis>
        <yAxes>
            <name>VIS2DATA</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>VISAMP</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>


        
                        
    <!-- plot (VisAmp - VisPhi) vs spatial freq -->    
    <plotDefinition>
        <id>VISAMP_VISPHI/SPATIAL_FREQ</id>
        <name>VisAmp and VisPhi vs. Spatial freq.</name>
        <skipFlaggedData>true</skipFlaggedData>
        <drawLine>false</drawLine>
        <xAxis>
            <name>SPATIAL_FREQ</name>
            <logScale>false</logScale>
            <includeZero>true</includeZero>
            <converter>MEGA_LAMBDA</converter>
        </xAxis>
        <yAxes>
            <name>VISAMP</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes>
        <yAxes>
            <name>VISPHI</name>
            <logScale>false</logScale>
            <includeZero>false</includeZero>
        </yAxes> 
    </plotDefinition>

    <!-- plot(VisAmp - VisPhi) vs wavelength -->    
    <plotDefinition>
